[package]
name = "livekit-api"
version = "0.1.3"
license = "Apache-2.0"
description = "Server SDK for livekit"
edition = "2021"

[features]
# By default ws TLS is not enabled
default = ["services", "access-token", "webhooks"]

signal-client = ["dep:tokio-tungstenite", "dep:tokio", "dep:futures-util", "dep:reqwest"]
services = ["dep:reqwest"]
access-token = ["dep:jsonwebtoken"]
webhooks = ["access-token", "dep:serde_json", "dep:base64"]

# Note that the following features only change the behavior of tokio-tungstenite.
# It doesn't change the behavior of libwebrtc/webrtc-sys
native-tls = ["tokio-tungstenite?/native-tls", "reqwest?/native-tls"]
native-tls-vendored = ["tokio-tungstenite?/native-tls-vendored", "reqwest?/native-tls-vendored"]
rustls-tls-native-roots = ["tokio-tungstenite?/rustls-tls-native-roots", "reqwest?/rustls-tls-native-roots"]
rustls-tls-webpki-roots = ["tokio-tungstenite?/rustls-tls-webpki-roots", "reqwest?/rustls-tls-webpki-roots"]
__rustls-tls = ["tokio-tungstenite?/__rustls-tls", "reqwest?/__rustls"]

[dependencies]
livekit-protocol = { path = "../livekit-protocol", version = "0.1.3" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.6"
url = "2.3.1"
log = "0.4"
parking_lot = { version = "0.12.1" }
prost = "0.11"

# webhooks
serde_json = { version = "1.0", optional = true }
base64 = { version = "0.21.2", optional = true }

# access_token & services
jsonwebtoken = { version = "8", default-features = false, optional = true }

# signal_client
tokio-tungstenite = { version = "0.20", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
futures-util = { version = "0.3", default-features = false, features = ["sink"], optional = true }

reqwest = { version = "0.11", default-features = false, features = ["json"], optional = true }