[package]
name = "webhooks"
version = "0.1.0"
edition = "2021"

[dependencies]
livekit-api = { version = "0.2.0", path = "../../livekit-api" }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15.7"
env_logger = "0.10.0"
livekit-protocol = { version = "0.2.0", path = "../../livekit-protocol" }
log = "0.4.20"
pretty_env_logger = "0.5.0"
livekit = { version = "0.2.0", path = "../../livekit", features = ["native-tls"] }
anyhow = "1.0.75"
