[package]
name = "livekit-ffi"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "LiveKit interface for foreign languages"
repository = "https://github.com/livekit/client-sdk-rust" 

[dependencies]
livekit = { path = "../livekit", version = "0.1.1" }
tokio = { version = "1.0", features = ["full"] }
parking_lot = { version = "0.12.1", features = ["send_guard"] }
prost = "0.11.0"
prost-types = "0.11.1"

[build-dependencies]
prost-build = { version = "0.11.1" }


[lib]
crate-type = ["cdylib", "staticlib"]
