[package]
name = "livekit-ffi"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "LiveKit interface for foreign languages"

[dependencies]
livekit = { path = "../livekit", version = "0.1.1" }
tokio = { version = "1.0", features = ["full"] }
