[workspace]
resolver = "2"
members = [
    "livekit",
    "livekit-api",
    "livekit-protocol",
    "livekit-ffi",
    "livekit-runtime",
    "libwebrtc",
    "soxr-sys",
    "webrtc-sys",
    "webrtc-sys/build",
]

[workspace.dependencies]
libwebrtc = { version = "0.3.7", path = "libwebrtc" }
livekit-api = { version = "0.4.1", path = "livekit-api" }
livekit-ffi = { version = "0.12.2", path = "livekit-ffi" }
livekit-protocol = { version = "0.3.6", path = "livekit-protocol" }
livekit-runtime = { version = "0.3.1", path = "livekit-runtime" }
livekit = { version = "0.7.0", path = "livekit" }
soxr-sys = { version = "0.1.0", path = "soxr-sys" }
webrtc-sys-build = { version = "0.3.5", path = "webrtc-sys/build" }
webrtc-sys = { version = "0.3.5", path = "webrtc-sys" }
