[workspace]
members = [
    "livekit",
    "livekit-api",
    "livekit-protocol",
    "livekit-ffi",
    "libwebrtc",
    "webrtc-sys",
    "webrtc-sys/build",
]

[patch.crates-io]
ring = { git = "https://github.com/1Password/ring", branch = "1p/release-0.16" }