[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update -y && apt-get install -y pkg-config:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH libx11-dev:$CROSS_DEB_ARCH libgl1-mesa-dev:$CROSS_DEB_ARCH libxext-dev:$CROSS_DEB_ARCH"
]