[package]
name = "webrtc-sys"
version = "0.1.0"
edition = "2021"
homepage = "https://livekit.io"

[dependencies]
cxx = "1.0"
log = "0.4"

[build-dependencies]
curl = "0.4"
tar = "0.4"
flate2 = "1.0"
cxx-build = "1.0"
glob = "0.3.0"
regex = "1.0"

[dev-dependencies]
env_logger = "0.9"

#[lib]
#crate-type = ["staticlib", "cdylib"]
