[package]
name = "rpc_example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
env_logger = "0.10"
livekit = { path = "../../livekit", features = ["native-tls"]}
livekit-api = { path = "../../livekit-api"}
log = "0.4"
