[package]
name = "playogg_from_disk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
livekit = { path = "../../livekit", version = "0.4.0" }
thiserror = "1.0.47"
log = "0.4.20"
env_logger = "0.10.0"
webrtc-media = "0.8.0"
byteorder = "1.5.0"

[workspace]
