[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full", "parking_lot"] }
livekit-api = { path = "../../livekit-api", version = "0.3.2", features = ["native-tls"] }
futures = "0.3"

