[package]
edition = "2021"
name = "wgpu_room"
version = "0.1.1"

[features]
default = []
tracing = ["console-subscriber", "tokio/tracing"]

[dependencies]
console-subscriber = {version = "0.1.10", features = ["parking_lot"], optional = true}
eframe = {version = "0.22.0", default-features = false, features = ["default_fonts", "wgpu", "persistence"]}
egui = "0.22.0"
egui-wgpu = "0.22.0"
env_logger = "0.10.0"
futures = "0.3"
image = "0.24"
livekit = {path = "../../livekit", version = "0.2.0", features = ["native-tls"]}
log = "0.4"
parking_lot = {version = "0.12.1", features = ["deadlock_detection"]}
screenshots = "0.8.4"
serde = {version = "1", features = ["derive"]}
tokio = {version = "1", features = ["full", "parking_lot"]}
wgpu = "0.16"
winit = "0.28"
