[package]
name = "wgpu_room"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
livekit = { path = "../../livekit", version = "0.1.3" }
futures = "0.3"
wgpu = "0.16"
winit = "0.28"
parking_lot = { version = "0.12.1", features=["deadlock_detection"] }
image = "0.24"
egui = "0.22"
egui-wgpu = { version = "0.22", features = ["winit"] }
egui-winit = "0.22"
log = "0.4"