[package]
name = "simple_room"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
livekit = { path = "../../livekit", version = "0.1.1" }
futures = "0.3"
wgpu = "0.14.0"
winit = "0.27.5"
parking_lot = "0.12.1"

egui = "0.20.1"
egui-wgpu = { version = "0.20.0", features = ["winit"] }
egui-winit = "0.20.1"

image = "0.24.5"
