[package]
name = "livekit-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
prost = "0.11"

[build-dependencies]
prost-build = { version = "0.11.1" }
