[package]
name = "livekit-protocol"
version = "0.1.3"
license = "Apache-2.0"
description = "Protocol for LiveKit server"
edition = "2021"

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
futures-util = { version = "0.3", features = ["sink"] }
parking_lot = "0.12"
prost = "0.11"
prost-types = "0.11"
