[package]
name = "livekit"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "Native SDK for LiveKit"
repository = "https://github.com/livekit/client-sdk-rust" 

[dependencies]
livekit-webrtc = { path = "../livekit-webrtc", version = "0.1.1" }
livekit-utils = { path = "../livekit-utils", version = "0.1.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio-tungstenite = { version = "0.18", features = ["native-tls"] }
tokio = { version = "1", features = ["full"] }
parking_lot = { version = "0.12.1", features = ["send_guard"] }
url = "2.2.2"
futures-util = "0.3.23"
thiserror = "1.0"
prost = "0.11.0"
prost-types = "0.11.1"
lazy_static = "1.4.0"
tracing = "0.1"

[build-dependencies]
prost-build = { version = "0.11.1" }
