[package]
name = "livekit"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "Native SDK for LiveKit"
repository = "https://github.com/livekit/client-sdk-rust" 

[features]
# By default ws TLS is not enabled
default = []

# Note that the following features only change the behavior of tokio-tungstenite.
# It doesn't change the behavior of libwebrtc/webrtc-sys
native-tls = ["tokio-tungstenite/native-tls"]
native-tls-vendored = ["tokio-tungstenite/native-tls-vendored"]
rustls-tls-native-roots = ["tokio-tungstenite/rustls-tls-native-roots"]
rustls-tls-webpki-roots = ["tokio-tungstenite/rustls-tls-webpki-roots"]
__rustls-tls = ["tokio-tungstenite/__rustls-tls"]

[dependencies]
livekit-webrtc = { path = "../livekit-webrtc", version = "0.1.1" }
livekit-protocol = { path = "../livekit-protocol", version = "0.1.0" }
prost = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio-tungstenite = { version = "0.19" }
tokio = { version = "1", features = ["full"] }
parking_lot = { version = "0.12.1" }
url = "2.3"
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
thiserror = "1.0"
lazy_static = "1.4"
log = "0.4"
