[package]
name = "livekit"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "Native SDK for LiveKit"
repository = "https://github.com/livekit/client-sdk-rust" 

[dependencies]
livekit-webrtc = { path = "../livekit-webrtc", version = "0.1.1" }
livekit-protocol = { path = "../livekit-protocol", version = "0.1.0" }
prost = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio-tungstenite = { version = "0.19", features = ["rustls-tls-native-roots"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
parking_lot = { version = "0.12.1", features = ["send_guard"] }
url = "2.3"
futures-util = "0.3"
thiserror = "1.0"
lazy_static = "1.4"
tracing = "0.1"
